INSERT INTO charactermodel (name, characterclass) VALUES ('Fabu', 'Mage');
INSERT INTO charactermodel (name, characterclass) VALUES ('John', 'Warrior');
INSERT INTO charactermodel (name, characterclass) VALUES ('Jane', 'Mage');
INSERT INTO charactermodel (name, characterclass) VALUES ('Mike', 'Rogue');
INSERT INTO charactermodel (name, characterclass) VALUES ('Emily', 'Paladin');
INSERT INTO charactermodel (name, characterclass) VALUES ('William', 'Hunter');
INSERT INTO charactermodel (name, characterclass) VALUES ('Olivia', 'Priest');
INSERT INTO charactermodel (name, characterclass) VALUES ('James', 'Druid');
INSERT INTO charactermodel (name, characterclass) VALUES ('Sophia', 'Warlock');
INSERT INTO charactermodel (name, characterclass) VALUES ('Benjamin', 'Monk');
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO statsmodel (level, totalexp, currentExp, expNeededNextLevel, health, currenthealth, atkpower, critchance) VALUES (1, 0, 0, 24, 10, 10, 1, 2);
INSERT INTO enemiesmodel (name, level, expgiven, health, currenthealth, atkpower) VALUES ('Rat', 1, 1, 1, 1, 1);
INSERT INTO enemiesmodel (name, level, expgiven, health, currenthealth, atkpower) VALUES ('Slime', 1, 1, 1, 1, 1);
INSERT INTO enemiesmodel (name, level, expgiven, health, currenthealth, atkpower) VALUES ('Skeleton', 1, 1, 1, 1, 1);
